package respcode

const (
	USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
	INVALID_OTP             = "INVALID_OTP"
	EMAIL_ALREADY_EXISTS    = "EMAIL_ALREADY_EXISTS"
	PHONE_ALREADY_EXISTS    = "PHONE_ALREADY_EXISTS"
)
